import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import WalletModal from "./components/WalletModal";
import { useAccount } from "wagmi";
import { Button, useDisclosure } from "@chakra-ui/react";

const Home: NextPage = () => {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const { data, isError, isLoading } = useAccount();

  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Minting Starter Kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mint an <a href="https://nextjs.org">NFT!</a>
        </h1>

        <p className={styles.description}>NFT Minting Starter Kit</p>

        {!data ? (
          <Button colorScheme="blue" size="lg" onClick={onOpen}>
            Connect Wallet
          </Button>
        ) : (
          <div>Account: {data?.address}</div>
        )}

        <WalletModal isOpen={isOpen} closeModal={onClose} />
      </main>
    </div>
  );
};

export default Home;
