import type { NextPage } from "next";
import Head from "next/head";
import styles from "@styles/Home.module.css";
import ConnectWallet from "@components/web3/ConnectWallet";

const Home: NextPage = () => {  

  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Minting Starter Kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mint an <a href="https://nextjs.org">NFT!</a>
        </h1>
        <p className={styles.description}>NFT Minting Starter Kit</p>
      </main>
    </div>
  );
};

export default Home;
